version: "2"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.35
    env_file:
      - ../env/mysql.env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./master-conf/:/etc/mysql
    ports:
      - "3306:3306"
